
CREATE TABLE MP_DESCUENTOS (
	MP_DESCUENTO_ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MP_NOMBRE       VARCHAR(60),
	MP_TIPO_BECA	VARCHAR (30)
					CHECK (MP_TIPO_BECA IN ('porcentaje', 'monto')),
	DESCRIPCION		TEXT,
	VALOR			NUMERIC (5,2)
);


ALTER TABLE [dbo].[MP_CRONOGRAMAPAGO]
ADD MONTO_FINAL float NULL,
	MONTO_DESCUENTO float NULL;

-- ALTER TABLE [dbo].[MP_CRONOGRAMAPAGO]
-- ADD FOREIGN KEY (MP_DESCUENTO_ID) REFERENCES MP_DESCUENTOS(MP_DESCUENTO_ID);

ALTER TABLE [dbo].[MP_MATRICULA]
ADD  MP_DESCUENTO_ID INT NULL;

ALTER TABLE [dbo].[MP_MATRICULA]
ADD FOREIGN KEY (MP_DESCUENTO_ID) REFERENCES MP_DESCUENTOS(MP_DESCUENTO_ID);



UPDATE MP_CRONOGRAMAPAGO
SET MONTO_FINAL = MP_CRO_MONTO;

