
CREATE TABLE MP_DESCUENTOS (
	MP_DESCUENTO_ID	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MP_NOMBRE       VARCHAR(60),
	MP_TIPO_BECA	VARCHAR (30)
					CHECK (MP_TIPO_BECA IN ('porcentaje', 'monto')),
	DESCRIPCION		TEXT,
	VALOR			NUMERIC (5,2)
);


ALTER TABLE [dbo].[MP_CRONOGRAMAPAGO]
ADD MONTO_COBRAR float NULL,
	MONTO_DESCUENTO float NULL;

-- ALTER TABLE [dbo].[MP_CRONOGRAMAPAGO]
-- ADD FOREIGN KEY (MP_DESCUENTO_ID) REFERENCES MP_DESCUENTOS(MP_DESCUENTO_ID);

ALTER TABLE [dbo].[MP_CRONOGRAMAPAGO]
ADD MONTO_COBRAR float NULL,
	MONTO_DESCUENTO float NULL;

ALTER TABLE [dbo].[MP_MATRICULA]
ADD FOREIGN KEY (MP_DESCUENTO_ID) REFERENCES MP_DESCUENTOS(MP_DESCUENTO_ID);



UPDATE MP_CRONOGRAMAPAGO
SET MONTO_COBRAR = MP_CRO_MONTO;



-- dOCUMENTOS
CREATE TABLE MP_MODULOS_SISTEMA (
	MP_MODULOS_SISTEMA_ID INT PRIMARY KEY NOT NULL IDENTITY ,
	MP_NOMBRE_MODULO VARCHAR (30) ,
	MP_NOMBRE_SUBMODULO VARCHAR (30) DEFAULT '' ,,
	MP_OBSERVACIONES TEXT NULL
);

INSERT INTO MP_MODULOS_SISTEMA (MP_NOMBRE_MODULO) VALUES
('pagos y matriculas'),
('notas academicas'),
('recursos humanos'),
('logistica');


CREATE TABLE MP_DOCUMENTOS (
	MP_DOCUMENTOS_ID INT PRIMARY KEY NOT NULL IDENTITY,
	MP_DIRECTORIO_ARCHIVO TEXT NULL,
	MP_NOMBRE_ARCHIVO VARCHAR (60) NULL,
    MP_TIPO_DOCUMENTO VARCHAR (30) DEFAULT 'ESTATICO',
	USU_ID INT NULL,
	MP_MODULOS_SISTEMA_ID INT NULL ,
	CONSTRAINT fk_usuario_documentos FOREIGN KEY (USU_ID) REFERENCES USUARIO (USU_ID),
	CONSTRAINT fk_modulo_sistema_documentos FOREIGN KEY (MP_MODULOS_SISTEMA_ID ) REFERENCES MP_MODULOS_SISTEMA(MP_MODULOS_SISTEMA_ID)
);


ALTER TABLE MP_TIPOCOMPROBANTE
ADD MP_TIPCOM_SIGLAS VARCHAR(8);

/*
    -- DATA PRUEBA

    INSERT INTO MP_DOCUMENTOS (MP_DIRECTORIO_ARCHIVO, MP_NOMBRE_ARCHIVO, USU_ID, MP_MODULOS_SISTEMA_ID ) VALUES
    ('tu_imaginacion/la_nube', 'un_archivo_imaginario1.docx', 21, 1 ),
    ('tu_imaginacion/la_nube', 'un_archivo_imaginario2.docx', 21, 1 ),
    ('tu_imaginacion/la_nube', 'un_archivo_imaginario3.docx', 21, 1 ),
    ('tu_imaginacion/la_nube', 'un_archivo_imaginario4.docx', 21, 1 );

*/

